In [238]:
import pandas as pd 
import numpy as np 

In [239]:
dataframe=pd.read_csv('/Users/sanatwalia/Desktop/Dataset/dataset.csv')

In [240]:
list1 =list(dataframe['Symptom_1'].unique())+list(dataframe['Symptom_2'].unique())+list(dataframe['Symptom_3'].unique())+list(dataframe['Symptom_4'].unique())+list(dataframe['Symptom_5'].unique())+list(dataframe['Symptom_6'].unique())+list(dataframe['Symptom_7'].unique())+list(dataframe['Symptom_8'].unique())+list(dataframe['Symptom_9'].unique())+list(dataframe['Symptom_10'].unique())+list(dataframe['Symptom_11'].unique())+list(dataframe['Symptom_12'].unique())+list(dataframe['Symptom_13'].unique())+list(dataframe['Symptom_1'].unique())+list(dataframe['Symptom_1'].unique())+list(dataframe['Symptom_1'].unique())+list(dataframe['Symptom_1'].unique())+list(dataframe['Symptom_1'].unique())+list(dataframe['Symptom_14'].unique())+list(dataframe['Symptom_15'].unique())+list(dataframe['Symptom_16'].unique())+list(dataframe['Symptom_17'].unique())

In [241]:

unique_list = []

for item in list1:
    if item not in unique_list:
        unique_list.append(item)

print(unique_list)

['itching', ' skin_rash', ' continuous_sneezing', ' shivering', ' stomach_pain', ' acidity', ' vomiting', ' indigestion', ' muscle_wasting', ' patches_in_throat', ' fatigue', ' weight_loss', ' sunken_eyes', ' cough', ' headache', ' chest_pain', ' back_pain', ' weakness_in_limbs', ' chills', ' joint_pain', ' yellowish_skin', ' constipation', ' pain_during_bowel_movements', ' breathlessness', ' cramps', ' weight_gain', ' mood_swings', ' neck_pain', ' muscle_weakness', ' stiff_neck', ' pus_filled_pimples', ' burning_micturition', ' bladder_discomfort', ' high_fever', ' nodal_skin_eruptions', ' ulcers_on_tongue', ' loss_of_appetite', ' restlessness', ' dehydration', ' dizziness', ' weakness_of_one_body_side', ' lethargy', ' nausea', ' abdominal_pain', ' pain_in_anal_region', ' sweating', ' bruising', ' cold_hands_and_feets', ' anxiety', ' knee_pain', ' swelling_joints', ' blackheads', ' foul_smell_of urine', ' skin_peeling', ' blister', ' dischromic _patches', ' watering_from_eyes', ' extr

In [242]:
import math

def has_nan(lst):
    for x in lst:
        if isinstance(x, float) and math.isnan(x):
            return True
    return False


if has_nan(unique_list):
    print("The list contains NaN values.")
else:
    print("The list does not contain NaN values.")

The list contains NaN values.


In [243]:
def remove_nan(lst):
    return [x for x in lst if not (isinstance(x, float) and math.isnan(x))]

cleaned_list = remove_nan(unique_list)

In [244]:
disease_names=cleaned_list

In [245]:
disease_names.append('disease')

In [246]:
df=pd.DataFrame(columns=disease_names)

In [247]:
disease_names

['itching',
 ' skin_rash',
 ' continuous_sneezing',
 ' shivering',
 ' stomach_pain',
 ' acidity',
 ' vomiting',
 ' indigestion',
 ' muscle_wasting',
 ' patches_in_throat',
 ' fatigue',
 ' weight_loss',
 ' sunken_eyes',
 ' cough',
 ' headache',
 ' chest_pain',
 ' back_pain',
 ' weakness_in_limbs',
 ' chills',
 ' joint_pain',
 ' yellowish_skin',
 ' constipation',
 ' pain_during_bowel_movements',
 ' breathlessness',
 ' cramps',
 ' weight_gain',
 ' mood_swings',
 ' neck_pain',
 ' muscle_weakness',
 ' stiff_neck',
 ' pus_filled_pimples',
 ' burning_micturition',
 ' bladder_discomfort',
 ' high_fever',
 ' nodal_skin_eruptions',
 ' ulcers_on_tongue',
 ' loss_of_appetite',
 ' restlessness',
 ' dehydration',
 ' dizziness',
 ' weakness_of_one_body_side',
 ' lethargy',
 ' nausea',
 ' abdominal_pain',
 ' pain_in_anal_region',
 ' sweating',
 ' bruising',
 ' cold_hands_and_feets',
 ' anxiety',
 ' knee_pain',
 ' swelling_joints',
 ' blackheads',
 ' foul_smell_of urine',
 ' skin_peeling',
 ' blister',

In [248]:
df['disease']=dataframe['Disease'].copy()


In [249]:
df

itching  skin_rash  continuous_sneezing  shivering  stomach_pain  \
0        NaN        NaN                  NaN        NaN           NaN   
1        NaN        NaN                  NaN        NaN           NaN   
2        NaN        NaN                  NaN        NaN           NaN   
3        NaN        NaN                  NaN        NaN           NaN   
4        NaN        NaN                  NaN        NaN           NaN   
...      ...        ...                  ...        ...           ...   
4915     NaN        NaN                  NaN        NaN           NaN   
4916     NaN        NaN                  NaN        NaN           NaN   
4917     NaN        NaN                  NaN        NaN           NaN   
4918     NaN        NaN                  NaN        NaN           NaN   
4919     NaN        NaN                  NaN        NaN           NaN   

      acidity  vomiting  indigestion  muscle_wasting  patches_in_throat  ...  \
0         NaN       NaN          NaN             NaN                NaN  ...   
1         NaN       NaN          NaN             NaN                NaN  ...   
2         NaN       NaN          NaN             NaN                NaN  ...   
3         NaN       NaN          NaN             NaN                NaN  ...   
4         NaN       NaN          NaN             NaN                NaN  ...   
...       ...       ...          ...             ...                ...  ...   
4915      NaN       NaN          NaN             NaN                NaN  ...   
4916      NaN       NaN          NaN             NaN                NaN  ...   
4917      NaN       NaN          NaN             NaN                NaN  ...   
4918      NaN       NaN          NaN             NaN                NaN  ...   
4919      NaN       NaN          NaN             NaN                NaN  ...   

      receiving_unsterile_injections  coma  sinus_pressure  palpitations  \
0                                NaN   NaN             NaN           NaN   
1                                NaN   NaN             NaN           NaN   
2                                NaN   NaN             NaN           NaN   
3                                NaN   NaN             NaN           NaN   
4                                NaN   NaN             NaN           NaN   
...                              ...   ...             ...           ...   
4915                             NaN   NaN             NaN           NaN   
4916                             NaN   NaN             NaN           NaN   
4917                             NaN   NaN             NaN           NaN   
4918                             NaN   NaN             NaN           NaN   
4919                             NaN   NaN             NaN           NaN   

      stomach_bleeding  runny_nose  congestion  blood_in_sputum  \
0                  NaN         NaN         NaN              NaN   
1                  NaN         NaN         NaN              NaN   
2                  NaN         NaN         NaN              NaN   
3                  NaN         NaN         NaN              NaN   
4                  NaN         NaN         NaN              NaN   
...                ...         ...         ...              ...   
4915               NaN         NaN         NaN              NaN   
4916               NaN         NaN         NaN              NaN   
4917               NaN         NaN         NaN              NaN   
4918               NaN         NaN         NaN              NaN   
4919               NaN         NaN         NaN              NaN   

      loss_of_smell                                  disease  
0               NaN                         Fungal infection  
1               NaN                         Fungal infection  
2               NaN                         Fungal infection  
3               NaN                         Fungal infection  
4               NaN                         Fungal infection  
...             ...                                      ...  
4915    

In [250]:
disease_names.pop()

'disease'

In [251]:
for index, row in dataframe.iterrows():
    for col_name in disease_names:
        if col_name in row.values:
            df.at[index, col_name] = 1
        else:
            df.at[index, col_name] = 2

In [252]:

disease_val=df['disease'].unique()

In [253]:
disease_key=[i for i in range(1,len(disease_val)+1)]

In [254]:
disease_dict=dict(zip(disease_key,disease_val))

In [255]:
dict_new=dict(zip(disease_val,disease_key))


In [256]:
def replace_with_dict_val( column_name):
    new_dict={'Fungal infection': 1,
 'Allergy': 2,
 'GERD': 3,
 'Chronic cholestasis': 4,
 'Drug Reaction': 5,
 'Peptic ulcer diseae': 6,
 'AIDS': 7,
 'Diabetes ': 8,
 'Gastroenteritis': 9,
 'Bronchial Asthma': 10,
 'Hypertension ': 11,
 'Migraine': 12,
 'Cervical spondylosis': 13,
 'Paralysis (brain hemorrhage)': 14,
 'Jaundice': 15,
 'Malaria': 16,
 'Chicken pox': 17,
 'Dengue': 18,
 'Typhoid': 19,
 'hepatitis A': 20,
 'Hepatitis B': 21,
 'Hepatitis C': 22,
 'Hepatitis D': 23,
 'Hepatitis E': 24,
 'Alcoholic hepatitis': 25,
 'Tuberculosis': 26,
 'Common Cold': 27,
 'Pneumonia': 28,
 'Dimorphic hemmorhoids(piles)': 29,
 'Heart attack': 30,
 'Varicose veins': 31,
 'Hypothyroidism': 32,
 'Hyperthyroidism': 33,
 'Hypoglycemia': 34,
 'Osteoarthristis': 35,
 'Arthritis': 36,
 '(vertigo) Paroymsal  Positional Vertigo': 37,
 'Acne': 38,
 'Urinary tract infection': 39,
 'Psoriasis': 40,
 'Impetigo': 41}
    
    return new_dict[column_name]

    



In [257]:
df['disease']=df['disease'].apply(replace_with_dict_val)

In [258]:
df

itching  skin_rash  continuous_sneezing  shivering  stomach_pain  \
0          1          1                    2          2             2   
1          2          1                    2          2             2   
2          1          2                    2          2             2   
3          1          1                    2          2             2   
4          1          1                    2          2             2   
...      ...        ...                  ...        ...           ...   
4915       2          2                    2          2             2   
4916       2          1                    2          2             2   
4917       2          2                    2          2             2   
4918       2          1                    2          2             2   
4919       2          1                    2          2             2   

      acidity  vomiting  indigestion  muscle_wasting  patches_in_throat  ...  \
0           2         2            2               2                  2  ...   
1           2         2            2               2                  2  ...   
2           2         2            2               2                  2  ...   
3           2         2            2               2                  2  ...   
4           2         2            2               2                  2  ...   
...       ...       ...          ...             ...                ...  ...   
4915        2         1            2               2                  2  ...   
4916        2         2            2               2                  2  ...   
4917        2         2            2               2                  2  ...   
4918        2         2            2               2                  2  ...   
4919        2         2            2               2                  2  ...   

      receiving_unsterile_injections  coma  sinus_pressure  palpitations  \
0                                  2     2               2             2   
1                                  2     2               2             2   
2                                  2     2               2             2   
3                                  2     2               2             2   
4                                  2     2               2             2   
...                              ...   ...             ...           ...   
4915                               2     2               2             2   
4916                               2     2               2             2   
4917                               2     2               2             2   
4918                               2     2               2             2   
4919                               2     2               2             2   

      stomach_bleeding  runny_nose  congestion  blood_in_sputum  \
0                    2           2           2                2   
1                    2           2           2                2   
2                    2           2           2                2   
3                    2           2           2                2   
4                    2           2           2                2   
...                ...         ...         ...              ...   
4915                 2           2           2                2   
4916                 2           2           2                2   
4917                 2           2           2                2   
4918                 2           2           2                2   
4919                 2           2           2                2   

      loss_of_smell disease  
0                 2       1  
1                 2       1  
2                 2       1  
3                 2       1  
4                 2       1  
...             ...     ...  
4915              2      37  
4916              2      38  
4917              2      39  
4918              2      40  
4919              2      41  

[4920 rows x 132 columns]

In [259]:
from sklearn.model_selection import train_test_split

In [286]:

y=df['disease'] 
X=df.drop('disease',axis=1) 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [287]:
from sklearn.ensemble import RandomForestClassifier

In [288]:
rfc=RandomForestClassifier(n_estimators=300,criterion='gini',random_state=42)

In [289]:
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=300, random_state=42)

In [290]:
prediction=rfc.predict(X_test)
print(prediction)

[38 38 33 ... 23 11 36]


In [265]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report 

In [266]:
model=SVC()

In [267]:
model.fit(X_train,y_train)


SVC()

In [268]:
predictions=model.predict(X_test)

In [269]:
print(confusion_matrix(y_test,predictions))

[[33  0  0 ...  0  0  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 43 ...  0  0  0]
 ...
 [ 0  0  0 ... 41  0  0]
 [ 0  0  0 ...  0 33  0]
 [ 0  0  0 ...  0  0 36]]


In [270]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        33
           2       1.00      1.00      1.00        36
           3       1.00      1.00      1.00        43
           4       1.00      1.00      1.00        31
           5       1.00      1.00      1.00        38
           6       1.00      1.00      1.00        31
           7       1.00      1.00      1.00        42
           8       1.00      1.00      1.00        35
           9       1.00      1.00      1.00        43
          10       1.00      1.00      1.00        48
          11       1.00      1.00      1.00        37
          12       1.00      1.00      1.00        39
          13       1.00      1.00      1.00        37
          14       1.00      1.00      1.00        38
          15       1.00      1.00      1.00        37
          16       1.00      1.00      1.00        35
          17       1.00      1.00      1.00        38
          18       1.00    

In [275]:
df1=df[0:1]

In [276]:
df1

itching  skin_rash  continuous_sneezing  shivering  stomach_pain  acidity  \
0       1          1                    2          2             2        2   

   vomiting  indigestion  muscle_wasting  patches_in_throat  ...  \
0         2            2               2                  2  ...   

   receiving_unsterile_injections  coma  sinus_pressure  palpitations  \
0                               2     2               2             2   

   stomach_bleeding  runny_nose  congestion  blood_in_sputum  loss_of_smell  \
0                 2           2           2                2              2   

  disease  
0       1  

[1 rows x 132 columns]

In [277]:
df1

itching  skin_rash  continuous_sneezing  shivering  stomach_pain  acidity  \
0       1          1                    2          2             2        2   

   vomiting  indigestion  muscle_wasting  patches_in_throat  ...  \
0         2            2               2                  2  ...   

   receiving_unsterile_injections  coma  sinus_pressure  palpitations  \
0                               2     2               2             2   

   stomach_bleeding  runny_nose  congestion  blood_in_sputum  loss_of_smell  \
0                 2           2           2                2              2   

  disease  
0       1  

[1 rows x 132 columns]

In [279]:
df1.drop('disease',axis=1)

itching  skin_rash  continuous_sneezing  shivering  stomach_pain  acidity  \
0       1          1                    2          2             2        2   

   vomiting  indigestion  muscle_wasting  patches_in_throat  ...  \
0         2            2               2                  2  ...   

   abnormal_menstruation  receiving_unsterile_injections  coma  \
0                      2                               2     2   

   sinus_pressure  palpitations  stomach_bleeding  runny_nose  congestion  \
0               2             2                 2           2           2   

   blood_in_sputum  loss_of_smell  
0                2              2  

[1 rows x 131 columns]

In [281]:
df1.at[0, 'itching'] = 2

In [282]:
df1

itching  skin_rash  continuous_sneezing  shivering  stomach_pain  acidity  \
0       2          1                    2          2             2        2   

   vomiting  indigestion  muscle_wasting  patches_in_throat  ...  \
0         2            2               2                  2  ...   

   receiving_unsterile_injections  coma  sinus_pressure  palpitations  \
0                               2     2               2             2   

   stomach_bleeding  runny_nose  congestion  blood_in_sputum  loss_of_smell  \
0                 2           2           2                2              2   

  disease  
0       1  

[1 rows x 132 columns]

In [291]:
rfc.predict(df1)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- disease
